# Generated by Django 3.2.5 on 2021-07-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ad_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='slider',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default=False, max_length=300),
        ),
    ]
