# Generated by Django 3.2.5 on 2021-08-14 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210814_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='time',
        ),
    ]
